### ISSUE TITLE
Amazing !

### ISSUE THREAD

**Issue by jiyocoin** [rupeedigitalassets/RUPEE#1]
https://github.com/rupeedigitalassets/RUPEE/blob/011102ece7c0a47d617dd88076c12db412784ded/src/net.cpp#L1176

This coin has no real dev team behind it its built via wallet builder and you are being taken for a ride

**Comment by rupeedigitalassets** [comment]
We are part of the relaunch team. New code will be pused in about three weeks, depending upon Diwali by our development team in India, they will modernizer the code. and fix any issues in it.  Will keep you posted on that. Work will be started by next week.
